[package]
name = "what_you_say"
version = "1.0.0"
edition = "2021"
rust-version = "1.75.0"
publish = false

[dependencies]
lingua = "1.6"
magnus = "0.7"

[lib]
name = "what_you_say"
crate-type = ["cdylib"]
