name: Test cruby build
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lib/what_you_say/version.rb"

env:
  CACHE_KEY_PREFIX: "cruby-v1"
  SUPPORTED_RUBY_VERSIONS: "3.1,3.2,3.3"
  LATEST_RUBY_VERSION: "3.3"

jobs:
  cruby-package:
    name: Compile native gem
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux

          - x86_64-darwin
          - arm64-darwin

          - x64-mingw-ucrt

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ env.LATEST_RUBY_VERSION }}"

      - uses: oxidize-rb/actions/cross-gem@main
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: "${{ env.SUPPORTED_RUBY_VERSIONS }}"

      - uses: oxidize-rb/actions/test-gem-build@main
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: "${{ env.SUPPORTED_RUBY_VERSIONS }}"
